### ISSUE TITLE
help with using container

### ISSUE THREAD

**Issue by wallybarnum** [xanderhendriks/action-build-stm32cubeide#15]
thanks for building this docker image.  I could use your help getting the arguments correct, and would appreciate your help.
I'm trying to do a GH Actions CI build of an ST project that originally is built with STCube on windows. 
I can build it in a headless fashion by copying the STCube folder to a C:/tools folder , cloning the repo and calling the headless build bat file in the st cube folder.  
If I try to do the exact same thing in a Windows platform in GitHub Actions, it does not build as it can't resolve the project, so no I am trying your linux docker image, but its not clear to me how to properly give it the right paths to my project and if there needs to be a workspace file.
The repo name is "user_milano". Gitub actions seems to clone it to a user_milano/user_milano directory.
Thanks for any help you can give!
W

my yml file is this:

```
name: docker-build


on:
  workflow_dispatch: #this enables a manual run button on the GH Actions page
  push:              #this kicks of a build when a push occurs
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest  # should we pin this to a specific  version?  probably.
  


    steps:    
      # checkout code, including submodule, which will need a personal access token (PAT)
      # https://stackoverflow.com/questions/65077036/how-to-checkout-submodule-in-github-action
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0  # get complete git history
        submodules: true # get the submodules
        token: ${{ secrets.PAT_TOKEN }}

    - name: cd and tree
      run: |
        echo "cd"
        cd
        echo "ls /home/runner/work/user_milano/user_milano/"
        ls -alf /home/runner/work/user_milano/user_milano/

    - name: cat .cproject
      run: |
        echo "cat /home/runner/work/user_milano/user_milano/.cproject"
        cat /home/runner/work/user_milano/user_milano/.project
      
    - name: Docker Build  
      uses: xanderhendriks/action-build-stm32cubeide@v6.0
      with:
        project-path: 'Volante'
        project-target: 'Volante/Debug'    
```

Ive attached my .project and .cproject files, which are located at the root of my repo.  Ive renamed them to txt files to GitHub will attach them.

The repo name is user_milano
The project name is Volante

I am not suppling an eclipse workspace.  My understanding of doing headless builds it that you should let the tool automatically make one itself, plus is bad form to be checking in workspaces anyway.

The critical section of the output of the Docker Build step is this:

```
Run xanderhendriks/action-build-stm32cubeide@v6.0
  with:
    project-path: Volante
    project-target: Volante/Debug
/usr/bin/docker run --name b73e5755b1a55246743108bba7313894326af_1021cb --label 9b73e5 --workdir /github/workspace --rm -e "INPUT_PROJECT-PATH" -e "INPUT_PROJECT-TARGET" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/user_milano/user_milano":"/github/workspace" 9b73e5:755b1a55246743108bba7313894326af  "Volante" "Volante/Debug"
Project: file:/github/workspace/Volante can't be found!
Stm32cubeide:
JVM terminated. Exit code=1
```

I'll attach the complete log too.

[0_build.txt](https://github.com/xanderhendriks/action-build-stm32cubeide/files/15372483/0_build.txt)

[cproject.txt](https://github.com/xanderhendriks/action-build-stm32cubeide/files/15372549/cproject.txt)

[project.txt](https://github.com/xanderhendriks/action-build-stm32cubeide/files/15372550/project.txt)
