### ISSUE TITLE
Setting inputs to the GitHub action.

### ISSUE THREAD

**Issue by crsz20** [xanderhendriks/action-build-stm32cubeide#9]
Hello, I am new to CI/CD and would like to include automated builds of an stm32CubeIDE project. However, I am struggling with setting the required inputs, per your repo's README instructions.

Here is my [repo](https://github.com/crsz20/blink_411/tree/test-ci-action), which has the following structure:

```
blink_411/
|-- .git/
|-- .github/
    |-- workflows/
        |-- my-action.yml
|-- Core/
|-- Drivers/
|-- .cproject
|-- .mxproject
|-- .project
|-- blink_f411.ioc
|-- blink_f411.launch
```

I accidentally left out a letter when creating my repo, so although the repo is named `blink_411`, the CubeIDE project is named `blink_f411`. I have tried using both as the input to your github action:

```yml
- name: Build STM32CubeIde project
  uses: xanderhendriks/action-build-stm32cubeide@v10.0
  with:
      project-path: 'blink_f411'
      project-target: 'blink_f411'
```

The Docker container is successfully built. However, this yields the following (trimmed) output:
```
Project: file:/github/workspace/blink_f411 can't be found!
...
WARNING: No Project matched "blink_f411". Skipping...
```

Using the `${GITHUB_WORKSPACE}` and `${{ github.workspace }}` has the same results. **May I please have some guidance as to how to satisfy the input requirements?** In the [Example Usage Steps](https://github.com/xanderhendriks/action-build-stm32cubeide/tree/master#example-usage), I am not sure what `target/STM32` is referring to.

**Comment by xanderhendriks** [comment]
Hi Cristian,

You can have a look at my [STM32 sample application](https://github.com/xanderhendriks/stm32-sample-application). It shows how to use the build action.

Looking at your code, you have the project file in the root of your repo. I have never used it this way, but I would assume that the action would be happy to pick that up if you do it this way:

```
- name: Build STM32CubeIde project
  uses: xanderhendriks/action-build-stm32cubeide@v10.0
  with:
      project-path: '.'
      project-target: 'blink_f411'
```
